//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolaStripe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GolaStripe.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Nav_Back {
            get {
                return ResourceManager.GetString("Nav_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to home.
        /// </summary>
        public static string Nav_BackHome {
            get {
                return ResourceManager.GetString("Nav_BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LangSwitch_Label {
            get {
                return ResourceManager.GetString("LangSwitch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Label_Order {
            get {
                return ResourceManager.GetString("Label_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Label_Product {
            get {
                return ResourceManager.GetString("Label_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Label_Amount {
            get {
                return ResourceManager.GetString("Label_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Label_Customer {
            get {
                return ResourceManager.GetString("Label_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Label_Country {
            get {
                return ResourceManager.GetString("Label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid on.
        /// </summary>
        public static string Label_PaidOn {
            get {
                return ResourceManager.GetString("Label_PaidOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Label_Date {
            get {
                return ResourceManager.GetString("Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string Label_Card {
            get {
                return ResourceManager.GetString("Label_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref.
        /// </summary>
        public static string Label_Ref {
            get {
                return ResourceManager.GetString("Label_Ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Label_Total {
            get {
                return ResourceManager.GetString("Label_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Col_Description {
            get {
                return ResourceManager.GetString("Col_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Col_Qty {
            get {
                return ResourceManager.GetString("Col_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Col_Price {
            get {
                return ResourceManager.GetString("Col_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Col_Amount {
            get {
                return ResourceManager.GetString("Col_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Status_Paid {
            get {
                return ResourceManager.GetString("Status_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Status_Pending {
            get {
                return ResourceManager.GetString("Status_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Status_Cancelled {
            get {
                return ResourceManager.GetString("Status_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string Status_Expired {
            get {
                return ResourceManager.GetString("Status_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid.
        /// </summary>
        public static string Status_Unpaid {
            get {
                return ResourceManager.GetString("Status_Unpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New charge.
        /// </summary>
        public static string New_Title {
            get {
                return ResourceManager.GetString("New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Stripe Checkout link to send to your customer. You won't be redirected to pay..
        /// </summary>
        public static string New_Intro {
            get {
                return ResourceManager.GetString("New_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string New_ProductName {
            get {
                return ResourceManager.GetString("New_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (USD).
        /// </summary>
        public static string New_Price {
            get {
                return ResourceManager.GetString("New_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer language.
        /// </summary>
        public static string New_CustomerLanguage {
            get {
                return ResourceManager.GetString("New_CustomerLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language the customer will see on the checkout page, the receipt and the email..
        /// </summary>
        public static string New_CustomerLanguageHint {
            get {
                return ResourceManager.GetString("New_CustomerLanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create payment link.
        /// </summary>
        public static string New_Submit {
            get {
                return ResourceManager.GetString("New_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a product name (max. 200 characters)..
        /// </summary>
        public static string Err_ProductName {
            get {
                return ResourceManager.GetString("Err_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid price. Use an amount between 0.50 and 99,999.99 USD..
        /// </summary>
        public static string Err_Price {
            get {
                return ResourceManager.GetString("Err_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn't create the payment link. Please try again..
        /// </summary>
        public static string Err_CreateCheckout {
            get {
                return ResourceManager.GetString("Err_CreateCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment link.
        /// </summary>
        public static string Link_Title {
            get {
                return ResourceManager.GetString("Link_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment link ready.
        /// </summary>
        public static string Link_Heading {
            get {
                return ResourceManager.GetString("Link_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending order created. Copy the link and send it to your customer..
        /// </summary>
        public static string Link_Created {
            get {
                return ResourceManager.GetString("Link_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy link.
        /// </summary>
        public static string Link_Copy {
            get {
                return ResourceManager.GetString("Link_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied..
        /// </summary>
        public static string Link_Copied {
            get {
                return ResourceManager.GetString("Link_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the link and copy it with Ctrl+C..
        /// </summary>
        public static string Link_CopyFallback {
            get {
                return ResourceManager.GetString("Link_CopyFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Checkout.
        /// </summary>
        public static string Link_OpenCheckout {
            get {
                return ResourceManager.GetString("Link_OpenCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create another.
        /// </summary>
        public static string Link_CreateAnother {
            get {
                return ResourceManager.GetString("Link_CreateAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Stripe Checkout link (Test). If the customer cancels, the order is marked Cancelled; if the session expires, it is marked Expired..
        /// </summary>
        public static string Link_Hint {
            get {
                return ResourceManager.GetString("Link_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Checkout language is fixed when the link is created. To use another language, create a new link..
        /// </summary>
        public static string Link_LangHint {
            get {
                return ResourceManager.GetString("Link_LangHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment receipt.
        /// </summary>
        public static string Receipt_Title {
            get {
                return ResourceManager.GetString("Receipt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order #{0}.
        /// </summary>
        public static string Receipt_OrderNumber {
            get {
                return ResourceManager.GetString("Receipt_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items.
        /// </summary>
        public static string Receipt_NoItems {
            get {
                return ResourceManager.GetString("Receipt_NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as PDF.
        /// </summary>
        public static string Receipt_SavePdf {
            get {
                return ResourceManager.GetString("Receipt_SavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the print dialog, choose &quot;Save as PDF&quot;..
        /// </summary>
        public static string Receipt_PrintHint {
            get {
                return ResourceManager.GetString("Receipt_PrintHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn't load the receipt..
        /// </summary>
        public static string Receipt_LoadError {
            get {
                return ResourceManager.GetString("Receipt_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn't load the receipt. Please try again later..
        /// </summary>
        public static string Receipt_LoadErrorTryLater {
            get {
                return ResourceManager.GetString("Receipt_LoadErrorTryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt not found.
        /// </summary>
        public static string Receipt_NotFoundTitle {
            get {
                return ResourceManager.GetString("Receipt_NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn't find a paid receipt for this link. Please make sure you copied the full link from the email..
        /// </summary>
        public static string Receipt_NotFoundBody {
            get {
                return ResourceManager.GetString("Receipt_NotFoundBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you need help, reply to the receipt email or contact us through golapr.com..
        /// </summary>
        public static string Receipt_HelpHint {
            get {
                return ResourceManager.GetString("Receipt_HelpHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session_id parameter is missing from the URL..
        /// </summary>
        public static string Success_MissingSession {
            get {
                return ResourceManager.GetString("Success_MissingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item_Default {
            get {
                return ResourceManager.GetString("Item_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Item_Payment {
            get {
                return ResourceManager.GetString("Item_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment cancelled.
        /// </summary>
        public static string Cancel_Title {
            get {
                return ResourceManager.GetString("Cancel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were not charged. You left Checkout or cancelled the payment..
        /// </summary>
        public static string Cancel_Body {
            get {
                return ResourceManager.GetString("Cancel_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order has been cancelled..
        /// </summary>
        public static string Cancel_JustCancelled {
            get {
                return ResourceManager.GetString("Cancel_JustCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order was already cancelled..
        /// </summary>
        public static string Cancel_AlreadyCancelled {
            get {
                return ResourceManager.GetString("Cancel_AlreadyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order is already marked as paid (no changes were made)..
        /// </summary>
        public static string Cancel_AlreadyPaid {
            get {
                return ResourceManager.GetString("Cancel_AlreadyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order is still pending; if the Stripe session expires, it will be marked as expired..
        /// </summary>
        public static string Cancel_StillPending {
            get {
                return ResourceManager.GetString("Cancel_StillPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn't find an order for this session..
        /// </summary>
        public static string Cancel_NotFound {
            get {
                return ResourceManager.GetString("Cancel_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn't update the order..
        /// </summary>
        public static string Cancel_Error {
            get {
                return ResourceManager.GetString("Cancel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment receipt - {0} - Order #{1}.
        /// </summary>
        public static string Email_Subject {
            get {
                return ResourceManager.GetString("Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, thank you for your payment. Here is your receipt..
        /// </summary>
        public static string Email_Greeting {
            get {
                return ResourceManager.GetString("Email_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}, thank you for your payment. Here is your receipt..
        /// </summary>
        public static string Email_GreetingName {
            get {
                return ResourceManager.GetString("Email_GreetingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View / download receipt.
        /// </summary>
        public static string Email_ViewReceipt {
            get {
                return ResourceManager.GetString("Email_ViewReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your payment..
        /// </summary>
        public static string Email_ThankYou {
            get {
                return ResourceManager.GetString("Email_ThankYou", resourceCulture);
            }
        }
    }
}
